[theme]
# Primary accent color for interactive elements
primaryColor = "#74BEE0"

# Background color for the main content area
backgroundColor = "#0B0C0F"  # Un negro ligeramente m치s claro

# Background color used for the sidebar and most interactive widgets
secondaryBackgroundColor = "#37207D"

# Background color for DataFrames and tables
tertiaryBackgroundColor = "#4D27F5"  # Nuevo: fondo m치s claro para tablas

# Color used for almost all text
textColor = "#4D27F5"

# Text color for DataFrames (a침adir esto si tu versi칩n de Streamlit lo soporta)
secondaryTextColor = "#E0E0E0"  # Un gris claro para mejor contraste

# Font family
font = "sans serif"
